### ISSUE TITLE
Error message from genpoly.

### ISSUE THREAD

**Issue by ProfLeao** [jewettaij/moltemplate#50] opened 2021-06-14 18:51 UTC
I have been getting this error message.
```
Traceback (most recent call last):
  File "genpoly_lt.py", line 1084, in <module>
    main()
  File "genpoly_lt.py", line 1071, in main
    genpoly.WriteLTFile(outfile)
  File "genpoly_lt.py", line 663, in WriteLTFile
    self.WritePolymer(outfile,
  File "genpoly_lt.py", line 703, in WritePolymer
    self.ChooseDirections(coords)
  File "genpoly_lt.py", line 605, in ChooseDirections
    self.direction_vects[0][d] = coords[1][d] - coords[0][d]
IndexError: list index out of range
```
My workflow is following the logic below.
a) Run: python3 moltemplate_files/sequence_generator.py CH3 CH2 8405 41 41 40
```
import sys

def sequence(mon_lst, pol_deg, dims_lattice, random= False):
    """
        Função para a geração das sequências de monômeros que serão adicionadas
        ao polímero simulado. Esta função deve receber uma lista com os 
        monômeros declarados na forma de strings na lista, o grau de 
        polimerização, e as dimensões X, Y e Z da rede onde serão realizadas as 
        simulações. 

        Parâmetros:
        ·mon_lst: Lista com monômeros para a geração da sequência, cada monômero
            deve possuir o formato "CH2" ou "CH3" por exemplo. O primeiro valor
            da lista será tratado como "cap"; primeiro e último monômero de 
            cada polímero. O segundo será entendido como composto intermediário
            para a cadeia. Nesta versão, se monômeros adicionais forem 
            adicionados então serão ignorados, em versões futuras desse código, 
            será implementada uma regra para a geração de listas de
            heteropolímeros.
        
        ·pol_deg: Inteiro com o grau de polimerização da cadeia. 
        ·dims_lattice: Lista com três elementos inteiros informando o número de 
            sítions respectivamente nas direções 'X', 'Y' e 'Z' do volume 
            simulado. 
        ·radom: Variável booleana que em versões futuras será utilizada para 
            determinar se a colocação de monômeros alienígenas em 
            heteropolímeros será randômica (True) ou padronizada (False).

    """
    try:
        num_sitios = dims_lattice[0] * dims_lattice[1] * dims_lattice[2]
        num_cadeias = num_sitios // pol_deg
        pol_cap, pol_body = mon_lst[0], mon_lst[1]
    except:
        return ValueError

    with open("cuts.txt", 'w') as f:
        line = 0
        with open("sequence.txt", 'w') as file:
            for i in range(num_cadeias):
                file.write(pol_cap + "\n")
                line+=1
                for j in range(pol_deg-2):
                    file.write(pol_body + "\n")
                    line+=1
                file.write(pol_cap + ".rot(180,0,0,1)" + "\n")
                line+=1
                f.write(f"{line}\n")
def main():
    mon_lst = sys.argv[1:3]
    sys.argv[3:7] = [int(i) for i in sys.argv[3:7]]
    pol_deg, dims_lattice =  sys.argv[3], sys.argv[4:7]
    try:
        sequence(mon_lst, pol_deg, dims_lattice)
    except ValueError:
        print("**** ERRO ****\n", "Parâmetros inválidos!")
        exit()
    print("Sequencias de monômeros e de cortes geradas com sucesso!")
if __name__ == "__main__":
    main()
```

and 
b) Run:  ./lattice_generatos.sh
```
#!/bin/bash
cwd=$(pwd)		  # salva o diretório atual

POL_CAP='CH3';       	# Extremidade dos polímeros
POL_BODY='CH2';       # Corpo do polímero, heteropolímeros serão implementados
						# em outras versões do sequence_generator.py

#						
NMONOMERS=8405;         # O número de monômeros HDPE2911 8553 no entanto, 
						# para a modelagem e organização da rede em formato 
						# paralelepípedico, este valor não é factível, optou-se
						# por reduzir o GD para 8405 e adcioná-lo a uma rede de
						# 40 41 41
						# Para essa definição foi utilizada a seguinte 
						# metodologia:
						# 8553 * 8 (numero cúbico) = 68424
						# raiz(68424,3) = 40,901 -> 40
						# 68424 / 40 = 1710,6 -> 1710
						# raiz(1710,2) = 41,352 -> 41 
						# Logo a rede possui 41x41x40 = 67240 sítios que 
						# segmentados em oito unidades poliméricas resulta em
						# um gd de 67240/8 = 8405  



B=1.5350                # comprimento de cada monômero
DENSITY=0.96;		  	# densidade do polímero
MOL_WEIGHT=120000	

Nx=41; Ny=41; Nz=40;    # numero de sites (locais para a existência de uma 
						# partícula) da rede .

sites=$Nx*$Ny*$Nz;

# Gera a rede
cd ndmansfield/src/
./ndmansfield -box $Nx $Ny $Nz -seed 0 -tstart 1 -tsave 2000 -tstop $sites > curve_lattice.raw
mv curve_lattice.raw $cwd
cd $cwd


# Interpolação e reescalonamento da rede
SCALE=`echo "($NMONOMERS*$B)/($Nx*$Ny*$Nz-1)" | bc -l`   #comprimento da cadeia / #número de sites
python3 interpolate_curve.py $NMONOMERS $SCALE < curve_lattice.raw > curve_smooth.raw

# Transferência de arquivos
mv curve_smooth.raw curve_lattice.raw cuts.txt sequence.txt moltemplate_files/
cd moltemplate_files/

# Criação das sequências de monômeros e cortes
#/sequence_generator.py $POL_CAP $POL_BODY $NMONOMERS $Nx $Ny $Nz

# Criação do inputs LAMMPS 
python3 genpoly_lt.py	-polymer-name 'HDPE2911'\
						-monomer-name 'alcano'  \
						-sequence 'sequence.txt'\
						-bond Backbone C C  \
						-header 'import "compass_published.lt"'\
        				        -header 'import "ch2group.lt"' \
						-header 'import "ch3group.lt"' \
						-cuts 'cuts.txt' \
						< curve_lattice.raw > hdpe2911.lt

rm curve_smooth.raw curve_lattice.raw cuts.txt sequence.txt
#moltemplate.sh ...
cd $cwd
```

All files can be found here: 
[files.zip](https://github.com/jewettaij/moltemplate/files/6650571/files.zip)

**Comment by jewettaij** [comment] 2021-06-15 08:22
Hi Reginaldo
   I can reproduce the error.  This should not happen.
   Thank you for the report and the complete input files.  I will reply by tomorrow (if not sooner).
Andrew

**Comment by jewettaij** [comment] 2021-06-15 08:34
The problem is the "cuts.txt" file.  It contains an entry "67240" which equals the length of the polymer (the number of monomers in the polymer).  In the future, the "genpoly_lt.py" should print out an error message when something like this happens, because you are asking it to cut the polymer between the 67240'th monomer and the 67241'th monomer (and there is no 67241'th monomer).  But for now, remove that line from your "cuts.txt" file and you should be fine.
Hopefully this gets you past your impass.

I'll close the issue once I've modified "genpoly_lt.py" to print out better error messages.
Thanks again for the report.
Glad to see someone using "genpoly_lt.py"

-Andrew

**Comment by ProfLeao** [comment] 2021-06-15 09:22
Works!!!
Wow, the solution really was simple and even obvious. Forgive me for not doing it myself.
Thank you so much @jewettaij .

-Reginaldo.

**Comment by jewettaij** [comment] 2021-06-15 09:26
Glad it helped.
Take care.

**Closed by jewettaij** 2021-06-15 09:26 UTC
