### ISSUE TITLE
cnt capillary example error

### ISSUE THREAD

**Issue by Ferdous083** [jewettaij/moltemplate#10] opened 2017-07-22 12:10 UTC
I'm new to moltemplate, i just installed it and tried to run the carbon nanotube capillary example, 
when i try to run the 'moltemplate.sh system.lt'
it shows this error
Error(ttree.StaticObj.Parse()): 
 Duplicate class/array "unitcells"
       This occurs near:
         "graphene_walls.lt", line 14
       and also near:
         "nanotube.lt", line 14
Could you help please?

**Comment by jewettaij** [comment] 2017-07-27 02:49
Thanks for reporting.  Unfortunately, I cannot reproduce your error.  Try getting a fresh copy of moltemplate, along with it's examples, and try again.  To eliminate any possible chance of any discrepancies, please try running these commands exactly:
git clone https://github.com/jewettaij/moltemplate moltemplate_tmp
cd moltemplate_tmp
virtualenv venv
source venv/bin/activate
pip install .
cd examples/force_field_explicit_parameters/nanotube+water/moltemplate_files/
moltemplate system.lt
Please let me know if, after running these commands, if you still run into the error you had before.  If so, I'll ask you more details about the environment you are using.  If I don't hear back from you in one week, I will close the issue.

**Comment by jewettaij** [comment] 2017-08-23 00:27
I'm closing this issue due to lack of information.  My suspicion is that Ferdous083 modified the .lt files in the "moltemplate_files" subdirectory (containing "graphene_walls.lt" and "nanotube.lt").  If anyone notices this problem with a fresh moltemplate installation, please reopen the issue.

**Closed by jewettaij** 2017-08-23 00:27 UTC
