### ISSUE TITLE
No module named moltemplate.lttree_check

### ISSUE THREAD

**Issue by Addiw7** [jewettaij/moltemplate#44] opened 2021-01-13 10:01 UTC
Dear All,

This issue was raised a few months ago but it is closed now and I can't really figure out the solution.

So, I installed moltemplate using 
```sudo pip3.8 install .```
command. I got this message in response:

```
WARNING: The directory '/home/dawid/.cache/pip' or its parent directory is not owned or is not writable by the current user. The cache has been disabled. Check the permissions and owner of that directory. If executing pip with sudo, you may want sudo's -H flag.
Processing /home/dawid/qsar/moltemplate/moltemplate
Requirement already satisfied: numpy in /usr/local/lib/python3.8/dist-packages (from moltemplate==2.19.4) (1.19.3)
Building wheels for collected packages: moltemplate
  Building wheel for moltemplate (setup.py) ... done
  Created wheel for moltemplate: filename=moltemplate-2.19.4-py3-none-any.whl size=947603 sha256=636b2825e6147f767754caf7f16cb1cf018a0eb5cadc160428c2ab31546e2073
  Stored in directory: /tmp/pip-ephem-wheel-cache-12keh4te/wheels/49/fb/77/543625cb3ecfa30c8a7d9be81a554a2159052b2ef9bffcf78e
Successfully built moltemplate
Installing collected packages: moltemplate
Successfully installed moltemplate-2.19.4
```
So apart from the WARNING, everything seems fine. However, if I run 
```moltemplate.sh system.lt```
I keep on getting this message
```Traceback (most recent call last):
  File "/usr/local/bin/lttree_check.py", line 5, in <module>
    from moltemplate.lttree_check import main
ImportError: No module named moltemplate.lttree_check
```

I can find the lttree_check.py script in my /usr/local/bin directory but there is no moltemplate module.
However in the directory where moltemplate was downloaded I found the moltemlpate.sh script:
/home/dawid/qsar/moltemplate/moltemplate/moltemplate/scripts/moltemplate.sh
When I run it, it seems to work. So I just want to let you know that the reason behind this error is that
moltemplate.sh does not know about the directory where it should look for the *.py modules.

**Comment by jewettaij** [comment] 2021-01-16 00:49
Hi Addiw
   Thanks very much for the bug report.  I tried installing moltemplate today using pip, and did not run into this error message.  Unfortunately, I can't reproduce the error.  If it helps, I am using the python distribution that comes with anaconda (python 3.7.4).

### Questions:

1) I'm curious to know what version of python you are using.  Did python come preinstalled, or did you install it yourself?
2) Do you have multiple versions of python installed on your system?  (Either python2+python3, or multiple different versions of python3.)
3) (Related question.)  What kind of OS are you using?  If you are running python on MacOS, are you using the version of python that comes with Xcode, or did you install it using brew or anaconda or something similar?  If you are running this on windows, then are you using WSL(Ubuntu), or HyperV, or VirtualBox with a linux virtual machine?  (And how did you install python on that virtual machine?)  Knowing that will help me give advice to other people who run into this error.
4) What happens when you run?
```
lttree_check.py system.lt
```

### Background: Why you need *lttree_check.py*
*moltemplate.sh* invokes the *lttree_check.py* script to check for syntax errors in your .LT files.  If *lttree_check.py* is not working, the moltemplate will probably proceed anyway.  This means the moltemplate examples will probably still work because they have no errors.  Unfortunately, without *lttree_check.py* working, your own system.lt files are likely to fail.  It's pretty easy to make mistakes while writing an .LT file.  (I make them all the time.)  Running *moltemplate.sh* without *lttree_check.py* would be like trying to compile a program that does not print any error messages when there is a syntax error somewhere in your code.

### Background: Pip pain
The error you are reporting is an installation issue that is specific to *pip*.  Getting moltemplate to work with *pip* has always been a pain because some of the code was written in BASH instead of python.  (A bad idea.)  Once pip is done with the python code, the contents of the .py files are reorganized in a way that makes debugging difficult.  For example, the version of *lttree_check.py* that I wrote does not contain the line "from moltemplate.lttree_check import main" that you see in the error message.  It's tricky for me to find the root cause of the error message especially remotely (without being able to reproduce the error).  But I can make a couple suggestions.  Please try them and let me know what works:

### Suggestions

1) Start with a clean environment.
a) Perhaps this is overkill, but if you have admin privileges on this computer, try creating a new user account.
b) I really recommend the version of python which comes with anaconda.  Try downloading it and installing it locally on this new user account (ie. /home/NEWUSER or /home/dawid, *not* /usr/local).  That way if something goes wrong, you can easily undo the damage.
2) Use a virtual environment
Whenever you are having difficulty installing any python package, its wise to use virtual environments.  That way if something goes wrong during installation, you can just delete the "venv" directory (and start a new terminal) and there is no danger of messing up the python distribution on your own machine.
First uninstall moltemplate:
```
pip uninstall moltemplate
```
Then reinstall it
```
git clone https://github.com/jewettaij/moltemplate ~/moltemplate
cd ~/moltemplate
python -m venv venv     # (this does not work in python2)
source venv/bin/activate
pip install .
```
Then try running *moltemplate.sh system.lt* again on one of the examples.  Does this fix the issue?  If this works, that's great.  However, you will have to enter "source ~/moltemplate/venv/bin/activate" into a terminal beforehand every time you want to run moltemplate.sh, because otherwise each terminal has no way of knowing that you want to use a virtual environment instead of the default python environment (which does not have moltemplate installed).
3) If you cannot get any of these methods to work, then as a last resort you can try installing moltemplate using the [manual method](https://github.com/jewettaij/moltemplate#manual-installation).  (Ie. by editing your PATH.)  *(If you decide to take this route, please let me know what kind of error messages you ran into using pip.)*

**Comment by jewettaij** [comment] 2021-01-25 00:48
Dear Addiw7
   I realize it is a non-trivial effort to report bugs, and I appreciate your effort so far.  But I can't solve the problem with the information I have so far.  If you only have time to respond to one question, please answer this one:  What happens when you type this command into your terminal (after having installed moltemplate using pip):
```
lttree_check.py
```
Specifically, do you get a "command not found" error, or does something else happen?
I would like to resolve this issue as soon as possible.
Andrew

**Comment by jewettaij** [comment] 2022-02-10 07:54
After one year, nobody else has confirmed this error.  I'm closing this issue.

**Closed by jewettaij** 2022-02-10 07:54 UTC
Labels: bug, unconfirmed
